# -*- coding: utf-8 -*-
"""customer_behavior_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aLGlX-K4ucNv5VP6586oEfp-GuyxWfs

## 1. Configuração do ambiente

Nesta etapa são importadas as bibliotecas necessárias para manipulação, análise e visualização dos dados.
"""

# imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import matplotlib.dates as mdates
from google.colab import drive

sns.set(style="whitegrid")

"""## 2. Conexão com o Google Drive

Nesta etapa é realizada a conexão com o Google Drive para acessar os arquivos utilizados no projeto.

"""

# conexao com drive

path = "/content/drive/MyDrive/Mate_homework/"

if not os.path.exists(path):
    print("Montando Drive...")
    drive.mount("/content/drive")

os.chdir(path)
print(f"Diretório atual: {os.getcwd()}")

"""## 3. Carregamento e visão geral dos dados

Objetivo: carregar as três tabelas do projeto e compreender sua estrutura, tipos de dados e quantidade de registros.

"""

# carregamento dos dados

events_df = pd.read_csv("events.csv")
products_df = pd.read_csv("products.csv")
countries_df = pd.read_csv("countries.csv")

print(events_df.info())
print(products_df.info())
print(countries_df.info())

"""Observação:

A tabela de vendas (events.csv) contém as informações transacionais.
A tabela de produtos (products.csv) apresenta as categorias associadas aos produtos.
A tabela de países (countries.csv) contém os dados geográficos utilizados na análise.

Nesta etapa foi possível identificar os tipos de dados de cada coluna e verificar a presença de valores ausentes.

## 4. Limpeza e padronização dos dados

Objetivo: tratar valores ausentes, padronizar formatos e preparar as tabelas para a etapa de integração e análise.

As principais ações realizadas foram:
- remoção de registros com valores ausentes em unidades vendidas;
- tratamento de códigos de país ausentes;
- criação da categoria "Desconhecido" para países não identificados;
- conversão de datas;
- criação da variável de tempo de entrega;
- remoção de duplicatas;
- padronização dos nomes das colunas e valores textuais.
"""

# limpeza e padronização

# Remover NaN em Units Sold
events_df = events_df.dropna(subset=["Units Sold"])

# Preencher Country Code nulo
events_df['Country Code'] = events_df['Country Code'].fillna('UNK')

# Adicionar país desconhecido
nova_linha = pd.DataFrame({
    'name': ['Desconhecido'],
    'alpha-2': ['UNK'],
    'alpha-3': ['UNK'],
    'region': ['Outros'],
    'sub-region': ['Outros']
})

countries_df = pd.concat([countries_df, nova_linha], ignore_index=True)

# Converter datas
events_df['Order Date'] = pd.to_datetime(events_df['Order Date'])
events_df['Ship Date'] = pd.to_datetime(events_df['Ship Date'])

# Criar coluna de diferença
events_df['Delivery_Time'] = events_df['Ship Date'] - events_df['Order Date']

# Remover duplicatas
events_df = events_df.drop_duplicates()

# Padronizar nomes de colunas
events_df.columns = events_df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')

# Padronizar sales_channel
events_df['sales_channel'] = events_df['sales_channel'].str.strip().str.lower()

# Renomear colunas auxiliares
products_df.rename(columns={'id': 'product_id', 'item_type': 'product_category'}, inplace=True)
countries_df.rename(columns={'alpha-3': 'country_code', 'name': 'country_name'}, inplace=True)

# Padronizar produtos e países
for df in [products_df, countries_df]:
    df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')

"""Resultado:

Após a limpeza, os dados ficaram padronizados e prontos para integração.
Os registros sem identificação de país foram mantidos na análise por meio da categoria "Desconhecido", associada à região "Outros", evitando perda de informações de vendas.

## 5. Integração das tabelas

Objetivo: unir as três tabelas (vendas, produtos e países) em um único DataFrame consolidado para permitir as análises posteriores.

A união foi realizada utilizando:
- product_id para associar categorias aos pedidos;
- country_code para associar informações geográficas.
"""

# união de tabelas

merge_df = events_df.merge(
    products_df[['product_id', 'product_category']],
    on='product_id',
    how='left'
)

final_df = merge_df.merge(
    countries_df[['country_code', 'country_name', 'region', 'sub_region']],
    on="country_code",
    how='left'
)

print(final_df.info())

"""Resultado:

Após a integração, o conjunto final passou a conter informações de vendas, categorias de produtos e dados geográficos em uma única estrutura, possibilitando a realização das análises solicitadas.

## 6. Criação de métricas e variáveis derivadas

Objetivo: criar indicadores financeiros e variáveis auxiliares necessárias para as análises de desempenho, tempo de entrega e comportamento temporal das vendas.

Foram calculadas:
- receita, custo total e lucro;
- tempo de entrega em dias;
- variáveis de tempo (ano, mês, mês/ano e dia da semana).
"""

# métricas e variáveis derivadas

# Métricas financeiras
final_df['revenue'] = final_df['units_sold'] * final_df['unit_price']
final_df['total_cost'] = final_df['units_sold'] * final_df['unit_cost']
final_df['profit'] = final_df['revenue'] - final_df['total_cost']

# Tempo de entrega
final_df['delivery_time'] = final_df['ship_date'] - final_df['order_date']
final_df['delivery_time_days'] = final_df['delivery_time'].dt.days

# Variáveis temporais
final_df['order_year'] = final_df['order_date'].dt.year
final_df['order_month'] = final_df['order_date'].dt.month
final_df['order_month_name'] = final_df['order_date'].dt.month_name()
final_df['year_month'] = final_df['order_date'].dt.to_period('M')


# Criar a coluna de dia da semana
final_df['order_weekday'] = final_df['order_date'].dt.day_name()

# Criar identificador de mês/ano para tendências temporais
final_df['month_year'] = final_df['order_date'].dt.to_period('M')

"""Resultado:

Com as novas variáveis, o conjunto de dados passou a permitir análises financeiras, temporais e logísticas, atendendo aos requisitos do projeto.

## 7. Métricas-chave de desempenho (KPIs)

Objetivo: calcular os principais indicadores gerais da empresa para obter uma visão consolidada do desempenho das vendas.

Foram considerados indicadores de volume, cobertura geográfica e resultados financeiros.
"""

# KPIS gerais

kpi_data = {
    'Métrica': [
        'Total de Pedidos',
        'Lucro Total',
        'Receita Total',
        'Custo Total',
        'Unidades Vendidas',
        'Países Abrangidos',
        'Regiões Abrangidas',
        'Sub-Regiões Abrangidas'
    ],
    'Valor': [
        final_df['order_id'].nunique(),
        final_df['profit'].sum(),
        final_df['revenue'].sum(),
        final_df['total_cost'].sum(),
        final_df['units_sold'].sum(),
        final_df['country_name'].nunique(),
        final_df['region'].nunique(),
        final_df['sub_region'].nunique()
    ]
}

kpi_df = pd.DataFrame(kpi_data)
print(kpi_df.to_markdown(index=False, floatfmt=",.2f"))

"""Resultado:

As métricas consolidadas apresentam uma visão geral do desempenho da empresa, incluindo volume de pedidos, receita, custos, lucro e abrangência geográfica das operações.

## 8. Análise de vendas por categoria

### 8.1 Receita por categoria

Objetivo: analisar como a receita total está distribuída entre as diferentes categorias de produtos.
"""

# vendas por categoria

category_sales = final_df.groupby('product_category')['revenue'].sum().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(data=category_sales, x='revenue', y='product_category')
plt.title('Receita por Categoria')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico mostra a participação de cada categoria na receita total, permitindo identificar quais produtos concentram maior volume financeiro nas vendas.

### 8.2 Receita por região

Objetivo: analisar a distribuição da receita entre as regiões geográficas presentes no conjunto de dados.
"""

# vendas por região

region_sales = final_df.groupby('region')['revenue'].sum().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(data=region_sales, x='revenue', y='region')
plt.title('Receita por Região')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico apresenta a receita total por região, permitindo comparar o desempenho geográfico das vendas.

### 8.3 Receita por canal de vendas

Objetivo: comparar a receita total entre os canais de vendas online e offline.
"""

# vendas por canal

channel_sales = final_df.groupby('sales_channel')['revenue'].sum().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=channel_sales, x='sales_channel', y='revenue')
plt.title('Receita por Canal de Vendas')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico permite visualizar a participação de cada canal na receita total, possibilitando a comparação do desempenho entre vendas online e offline.

## 9. Análise do tempo entre pedido e envio

### 9.1 Tempo médio de envio por categoria

Objetivo: analisar o tempo médio de envio dos pedidos para cada categoria de produto.
"""

# tempo de envio por categoria

delivery_category = final_df.groupby('product_category')['delivery_time_days'].mean().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(data=delivery_category, x='delivery_time_days', y='product_category')
plt.title('Tempo Médio de Envio por Categoria')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico apresenta o tempo médio de envio por categoria, permitindo comparar diferenças no prazo logístico entre os produtos.

### 9.2 Tempo médio de envio por região

Objetivo: analisar como o tempo médio de envio varia entre as diferentes regiões geográficas.
"""

# tempo de envio por região

delivery_region = final_df.groupby('region')['delivery_time_days'].mean().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(data=delivery_region, x='delivery_time_days', y='region')
plt.title('Tempo Médio de Envio por Região')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico mostra o tempo médio de envio por região, permitindo avaliar possíveis diferenças logísticas entre os mercados atendidos.

### 9.3 Relação entre lucro e tempo de envio

Objetivo: verificar se existe relação entre o tempo necessário para o envio e o lucro médio obtido nos pedidos.
"""

# lucro vs tempo de envio
profit_vs_delivery = final_df.groupby('delivery_time_days')['profit'].mean().reset_index()

plt.figure(figsize=(10,6))
sns.regplot(data=profit_vs_delivery, x='delivery_time_days', y='profit')
plt.title('Lucro Médio vs Tempo de Envio')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico de dispersão com linha de tendência permite observar a relação entre tempo de envio e lucro médio, indicando se existe associação entre essas variáveis.

## 10. Dinâmica de vendas ao longo do tempo

### 10.1 Tendência de vendas por categoria

Objetivo: analisar a evolução da receita ao longo do tempo para cada categoria de produto.
"""

# dinâmica de vendas ao longo do tempo

monthly_category = final_df.groupby(['year_month','product_category'])['revenue'].sum().reset_index()
monthly_category['year_month'] = monthly_category['year_month'].dt.to_timestamp()

plt.figure(figsize=(12,6))
sns.lineplot(data=monthly_category, x='year_month', y='revenue', hue='product_category')
plt.xticks(rotation=45)
plt.title('Dinâmica de Vendas por Categoria')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico mostra a variação da receita ao longo do tempo para cada categoria, permitindo observar oscilações e tendências nas vendas.

### 10.2 Tendência de vendas por região

Objetivo: analisar a evolução da receita ao longo do tempo considerando as diferentes regiões geográficas.
"""

# dinâmica de vendas por região ao longo do tempo

monthly_region = final_df.groupby(['month_year', 'region'])['revenue'].sum().reset_index()
monthly_region['month_year'] = monthly_region['month_year'].dt.to_timestamp()

plt.figure(figsize=(14,7))
sns.lineplot(data=monthly_region, x='month_year', y='revenue', hue='region')
plt.title('Tendência de Vendas por Região')
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico mostra a variação da receita ao longo do tempo por região, permitindo comparar o comportamento das vendas entre os mercados analisados.

## 11. Análise de vendas por dia da semana

Objetivo: avaliar a distribuição da receita ao longo dos dias da semana para identificar possíveis padrões de comportamento nas vendas.
"""

# vendas por dia da semana

weekday_sales = final_df.groupby('order_weekday')['revenue'].sum().reindex(
    ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
)

# Agora o gráfico vai funcionar pois 'weekday_sales' existe
plt.figure(figsize=(10,6))
sns.barplot(x=weekday_sales.index, y=weekday_sales.values, hue=weekday_sales.index, palette='viridis', legend= False)
plt.xticks(rotation=45)
plt.title('Receita por Dia da Semana')
plt.xlabel('Dia da Semana')
plt.ylabel('Receita Total')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico apresenta a receita total por dia da semana, permitindo comparar o desempenho das vendas entre os diferentes dias.

## 12. Análise de sazonalidade

### 12.1 Unidades vendidas por mês e categoria

Objetivo: analisar o comportamento das vendas ao longo dos meses para identificar variações sazonais nas categorias de produtos.
"""

# análise de sazonalidade (unidades vendidas por mês)

seasonal_data = final_df.groupby(['order_month', 'product_category'])['units_sold'].sum().reset_index()

plt.figure(figsize=(14,7))
sns.lineplot(data=seasonal_data, x='order_month', y='units_sold', hue='product_category', marker='o')
plt.title('Sazonalidade: Unidades Vendidas por Mês e Categoria')
plt.xticks(range(1, 13))
plt.xlabel('Mês')
plt.ylabel('Total de Unidades')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico apresenta a variação das unidades vendidas por mês para cada categoria, permitindo observar mudanças no volume de vendas ao longo do ano.

### 12.2 Média de unidades vendidas por mês

Objetivo: analisar a média de unidades vendidas ao longo dos meses para identificar padrões sazonais nas categorias de produtos.
"""

# análise de sazonalidade por categoria de produto

# Agrupando por mês para identificar padrões sazonais anuais
seasonal_trends = final_df.groupby(['order_month', 'product_category'])['units_sold'].mean().reset_index()

plt.figure(figsize=(14,7))
sns.lineplot(data=seasonal_trends, x='order_month', y='units_sold', hue='product_category', marker='o')
plt.title('Sazonalidade: Média de Unidades Vendidas por Mês')
plt.xticks(range(1, 13))
plt.xlabel('Mês do Ano')
plt.ylabel('Média de Unidades Vendidas')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico apresenta a média de unidades vendidas por mês para cada categoria, permitindo observar variações sazonais no comportamento das vendas.

## 13. Análise geográfica das vendas

### 13.1 Top 10 países por receita

Objetivo: identificar os países com maior contribuição para a receita total da empresa.
"""

# análise de vendas por país (top 10)

country_sales = final_df.groupby('country_name')['revenue'].sum().nlargest(10).reset_index()

plt.figure(figsize=(12,6))
sns.barplot(data=country_sales, x='revenue', y='country_name', hue= 'country_name', palette='viridis', legend=False)
plt.title('Top 10 Países por Receita')
plt.xlabel('Receita Total')
plt.ylabel('País')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico apresenta os dez países com maior receita acumulada, permitindo observar a concentração geográfica das vendas.

### 13.2 Top 10 países com maior tempo médio de envio

Objetivo: identificar os países que apresentam maior tempo médio entre pedido e envio.
"""

# tempo de envio por país (top 10 maiores tempos)

delivery_country = final_df.groupby('country_name')['delivery_time_days'].mean().nlargest(10).reset_index()

plt.figure(figsize=(12,6))
sns.barplot(data=delivery_country, x='delivery_time_days', y='country_name', hue='country_name', palette='magma', legend=False)
plt.title('Top 10 Países com Maior Tempo Médio de Envio')
plt.xlabel('Dias Médios para Envio')
plt.ylabel('País')
plt.tight_layout()
plt.show()

"""Resultado:

O gráfico apresenta os dez países com maior tempo médio de envio, permitindo observar possíveis diferenças logísticas entre os mercados atendidos.

## 14. Conclusões

A análise dos dados permitiu obter uma visão abrangente das operações da empresa sob perspectivas financeira, geográfica, temporal e logística.

Em termos de desempenho financeiro, a empresa apresenta volume expressivo de receita e lucro, com concentração significativa em determinadas categorias de produtos. Isso indica que parte relevante do resultado está associada a um grupo específico de itens.

Do ponto de vista geográfico, a receita não está distribuída de forma homogênea entre as regiões e países, havendo concentração em determinados mercados. Esse padrão evidencia a importância estratégica dessas regiões para o desempenho geral da empresa.

Na comparação entre canais de vendas, foi possível observar diferença no volume de receita entre online e offline, indicando que ambos possuem relevância nas operações comerciais.

A análise logística mostrou variações no tempo médio de envio entre categorias, regiões e países. No entanto, a relação entre tempo de envio e lucro não demonstrou associação forte, sugerindo que o prazo de envio, dentro do intervalo observado, não impacta diretamente a rentabilidade média.

A avaliação temporal indicou oscilações nas vendas ao longo dos meses e diferenças no desempenho por dia da semana, permitindo identificar padrões de comportamento nas vendas ao longo do tempo.

De forma geral, o projeto possibilitou consolidar dados de múltiplas fontes, realizar tratamento e padronização das informações, calcular indicadores-chave e produzir análises visuais que apoiam a compreensão do desempenho operacional e comercial da empresa.
"""